name: Unit Tests Action
description: Action to run unit tests using pytest
inputs:
  python_version:
    description: "Python version you want to use"
    default: '3.10'
  requirements_path:
    description: "Folder path to the requirements.txt file"
    required: true
    default: ./requirements.txt
  unit_test_path:
    description: "Folder that contains code you want to test"
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ inputs.requirements_path }}

    - name: Run unit tests
      shell: bash
      run: |
        pytest ${{ inputs.unit_test_path }}
