name: Greeting data academy

on:
  push:
    branches: [main]

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 9th edition, this is Thursday 's first exercise! I'm $GREETING_ACTOR!'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 9th edition, this is $DAY_OF_WEEK's second exercise!"
        env:
          ACADEMY_TYPE: Data
  week_job:
    runs-on: self-hosted
    needs: greeting_job
    env:
      var1: asd
      var2: qwe
    steps:
      - name: "Test week job"
        run: echo "$var1 and $var2 weekly"
  unit_tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: ./.github/unit-tests-action/
  



