name: Lint SQL

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the version you need

    - name: Install sqlfluff
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff

    - name: Lint SQL files
      run: |
        echo "Current Working Directory:"
        pwd  # Print the current working directory
        echo "Linting SQL files..."
        sqlfluff lint ./*.sql --dialect mysql

