name: Lint SQL

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run SQL Linter
      uses: ./github/actions/sql-linter # Path to your local action
      with:
        dialect: "mysql"


# name: Lint SQL

# on:
#   push:
#     branches-ignore:
#       - main
#   pull_request:

# jobs:
#   lint:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install sqlfluff
#       run: |
#         python -m pip install --upgrade pip
#         pip install sqlfluff
    
#     - name: Auto-Fix SQL Files
#       run: sqlfluff fix ./*.sql --dialect mysql

#     - name: Lint SQL files
#       run: |
#         echo "Current Working Directory:"
#         pwd  # Print the current working directory
#         echo "Linting SQL files..."
#         sqlfluff lint ./*.sql --dialect mysql

